### ISSUE TITLE
Add reusable toast messages component

### ISSUE THREAD

**Issue by lyzadanger** [hypothesis/frontend-shared#1075]
We have an upcoming need for toast messages in a new application. The `client` application already has toast messages. Extract and add a toast message component to this package.

**Comment by lyzadanger** [comment]
As of now, I'm not entirely convinced we need the full toast-message functionality for this application. Perhaps. But the new `Callout` component released in v6.4.0 might do the trick.

**Comment by acelaya** [comment]
Since on first pass we are creating the component directly in via, I'll remove the "video annotations" label from this ticket.

Once https://github.com/hypothesis/via/pull/1125 is merged, I will do further testing on how to use the component in `client`, and adapt where needed.

Once both projects can use this component, we can probably get back to this issue and move the component to frontend-shared.
